<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="4" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1526" started-at="2019-09-18T05:39:26Z" finished-at="2019-09-18T05:39:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1526" started-at="2019-09-18T05:39:26Z" finished-at="2019-09-18T05:39:27Z">
      <class name="com.edu.test.SkuListTest">
        <test-method status="FAIL" signature="TestSkuList1()[pri:0, instance:com.edu.test.SkuListTest@26be92ad]" name="TestSkuList1" duration-ms="1183" started-at="2019-09-18T05:39:26Z" finished-at="2019-09-18T05:39:27Z">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[the Text: 'message1' is not Present!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: the Text: 'message1' is not Present!
at com.edu.utils.Checker.verifyTextPresent(Checker.java:40)
at com.edu.test.SkuListTest.TestSkuList1(SkuListTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSkuList1 -->
        <test-method status="PASS" signature="TestSkuList2()[pri:0, instance:com.edu.test.SkuListTest@26be92ad]" name="TestSkuList2" duration-ms="104" started-at="2019-09-18T05:39:27Z" finished-at="2019-09-18T05:39:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSkuList2 -->
        <test-method status="PASS" signature="TestSkuListById()[pri:0, instance:com.edu.test.SkuListTest@26be92ad]" name="TestSkuListById" duration-ms="97" started-at="2019-09-18T05:39:27Z" finished-at="2019-09-18T05:39:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSkuListById -->
        <test-method status="PASS" signature="TestSkuListByWrongIdType()[pri:0, instance:com.edu.test.SkuListTest@26be92ad]" name="TestSkuListByWrongIdType" duration-ms="90" started-at="2019-09-18T05:39:27Z" finished-at="2019-09-18T05:39:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestSkuListByWrongIdType -->
      </class> <!-- com.edu.test.SkuListTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
